[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  VITE_API_URL = "https://your-backend-api.herokuapp.com"
  VITE_WS_URL = "wss://your-backend-api.herokuapp.com"

[context.deploy-preview.environment]
  VITE_API_URL = "http://localhost:8000"
  VITE_WS_URL = "ws://localhost:8000"

[context.branch-deploy.environment]
  VITE_API_URL = "http://localhost:8000"
  VITE_WS_URL = "ws://localhost:8000"
